import * as fs from 'node:fs';
import * as path from 'node:path';
import { spawn } from 'node:child_process';
import { bold, cyan, dim, err, info, ok, warn } from '../util/print';
import { confirm } from '../util/prompt';

type PackageManager = 'pnpm' | 'yarn' | 'npm';

export async function init(args: string[]): Promise<number> {
  const cwd = process.cwd();
  const pkgPath = path.join(cwd, 'package.json');
  if (!fs.existsSync(pkgPath)) {
    err('No package.json found in this directory.');
    info(dim('  Run this from the root of your Node.js project.'));
    return 1;
  }

  const skipInstall = args.includes('--no-install');
  const force = args.includes('--force');

  const pm = detectPackageManager(cwd);
  info(`${dim('Project:')} ${cwd}`);
  info(`${dim('Package manager:')} ${pm}`);
  info('');

  if (!skipInstall) {
    const ok = await runInstall(pm, '@zero-gate/sdk');
    if (!ok) {
      warn('Install failed — you can re-run with --no-install and add the dep manually.');
      return 1;
    }
  } else {
    info(dim('Skipping install (--no-install).'));
  }

  const envPath = path.join(cwd, '.env.local');
  const examplePath = path.join(cwd, 'zero.example.ts');

  await writeIfMissing(envPath, ENV_TEMPLATE, force);
  await writeIfMissing(examplePath, EXAMPLE_TEMPLATE, force);

  info('');
  ok('Project ready.');
  info('');
  info(`  ${bold('Next steps')}`);
  info(`  1. Run ${cyan('zero agents create')} to provision an agent`);
  info(`  2. Paste ${cyan('ZERO_AGENT_ID')} and ${cyan('ZERO_API_SECRET')} into ${cyan('.env.local')}`);
  info(`  3. ${cyan('node --env-file=.env.local zero.example.ts')} (or your usual runner) to test`);
  return 0;
}

function detectPackageManager(cwd: string): PackageManager {
  if (fs.existsSync(path.join(cwd, 'pnpm-lock.yaml'))) return 'pnpm';
  if (fs.existsSync(path.join(cwd, 'yarn.lock'))) return 'yarn';
  return 'npm';
}

function runInstall(pm: PackageManager, dep: string): Promise<boolean> {
  return new Promise(resolve => {
    const args = pm === 'yarn' ? ['add', dep] : ['install', dep];
    info(`${dim('$')} ${pm} ${args.join(' ')}`);
    const child = spawn(pm, args, { stdio: 'inherit', shell: process.platform === 'win32' });
    child.on('exit', code => resolve(code === 0));
    child.on('error', e => {
      err(`Failed to run ${pm}: ${e.message}`);
      resolve(false);
    });
  });
}

async function writeIfMissing(file: string, content: string, force: boolean): Promise<void> {
  const exists = fs.existsSync(file);
  if (exists && !force) {
    const overwrite = await confirm(`${path.basename(file)} exists — overwrite?`);
    if (!overwrite) {
      info(`${dim('skip')} ${path.basename(file)}`);
      return;
    }
  }
  fs.writeFileSync(file, content);
  ok(`wrote ${path.basename(file)}`);
}

const ENV_TEMPLATE = `# Zero Gate credentials — generated by \`zero init\`.
# Run \`zero agents create\` and paste the values from its output.
ZERO_AGENT_ID=
ZERO_API_SECRET=
`;

const EXAMPLE_TEMPLATE = `import { ZeroGateSDK } from '@zero-gate/sdk';

async function main() {
  const gate = new ZeroGateSDK();
  const result = await gate.run();
  if (!result.allowed) {
    console.error('Blocked by Zero Gate.');
    process.exit(1);
  }
  console.log('Allowed. Token:', result.token);
}

main().catch(e => {
  console.error(e);
  process.exit(1);
});
`;
